### ISSUE TITLE
Hang and timeout on import alibabacloud-iot20180120==3.0.14

### ISSUE THREAD

**Issue by ejdoh1** [aliyun/alibabacloud-python-sdk#20]
When importing alibabacloud-iot20180120 versions 3.0.14 & 3.0.9  in Aliyun Function Compute, the import hangs and times-out the function invocation.
Function compute runtime Python 3.9

**Comment by TsinghuaDream** [comment]
It seems to be a problem with Aliyun Function Compute. If you have similar problems in the future, please give us timely feedback through work orders. Thank you very much.

https://smartservice.console.aliyun.com/service/create-ticket
