### ISSUE TITLE
compatibility in revised version release

### ISSUE THREAD

**Issue by calmzhu** [aliyun/alibabacloud-python-sdk#23]
In function [ListBucketsHeaders](https://github.com/aliyun/alibabacloud-python-sdk/blob/70555da239e8ff94f0c26e2b2eb4e75c105b9986/oss-20190517/alibabacloud_oss20190517/client.py#L4838)'s param header
it's type changed from dict( in alibabacloud-oss20190517==1.0.5) to object oss_20190517_models.ListBucketsHeader(in alibabacloud-oss20190517==1.0.5)
This is an broken change,it should NEVER be in revisied versions.

**Comment by TsinghuaDream** [comment]
Try this SDK. https://www.alibabacloud.com/help/en/oss/developer-reference/python
alibabacloud-oss20190517 is still optimized internally.
