### ISSUE TITLE
nodepool_name required in DescribeClusterNodePools API 

### ISSUE THREAD

**Issue by Patrix2001** [aliyun/alibabacloud-python-sdk#28]
Please improve calling for API https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/developer-reference/api-cs-2015-12-15-describeclusternodepools

I dont know nodepool name must required to running the DescribeClusterNodePoolsRequest program

```
def list_node_pool(client, ClusterId):
    request = cs_20151215_models.DescribeClusterNodePoolsRequest(cluster_id=ClusterId)
    runtime = util_models.RuntimeOptions()
    try:
        response = client.describe_cluster_node_pools_with_options(request, runtime)
        return response.body.servers
    except Exception as error:
        print(f"Error: {error}")
        return None
```

Error: TypeError: DescribeClusterNodePoolsRequest.__init__() got an unexpected keyword argument 'get_cluster_id'

DescribeClusterNodePoolsRequest module: https://github.com/aliyun/alibabacloud-python-sdk/blob/aa40b82e01b4c4312b123725891ca2383fd25df0/cs-20151215/alibabacloud_cs20151215/models.py#L10054

**Comment by TsinghuaDream** [comment]
1. Update your sdk version. pip install alibabacloud_cs20151215==4.3.0
2. code like this ` resp = client.describe_cluster_node_pools_with_options('cluster_id', headers, runtime)`

**Comment by Patrix2001** [comment]
@TsinghuaDream we want simplify your code calling, https://api.alibabacloud.com/api/CS/2015-12-15/DescribeClusterNodePools?tab=DEMO&lang=PYTHON&params={}

You can see nodepoolname is required, but the parameter does not required in console
![20240619195550](https://github.com/aliyun/alibabacloud-python-sdk/assets/61679822/89937dda-a914-469a-b46b-ee8719a9ae4c)
