### ISSUE TITLE
@TsinghuaDream we want simplify your code calling, https://api.alibabacloud.com/api/CS/2015-12-15/DescribeClusterNodePools?tab=DEMO&lang=PYTHON&params={}

### ISSUE THREAD

**Issue by JuanPatrix** [aliyun/alibabacloud-python-sdk#29]
@TsinghuaDream we want simplify your code calling, https://api.alibabacloud.com/api/CS/2015-12-15/DescribeClusterNodePools?tab=DEMO&lang=PYTHON&params={}

You can see nodepoolname is required, but the parameter does not required in console
![20240619195550](https://github.com/aliyun/alibabacloud-python-sdk/assets/61679822/89937dda-a914-469a-b46b-ee8719a9ae4c)

_Originally posted by @Patrix2001 in https://github.com/aliyun/alibabacloud-python-sdk/issues/28#issuecomment-2178658568_

**Comment by TsinghuaDream** [comment]
it is not required,Even currently you cannot pass nodepoolname.
