### ISSUE TITLE
python 升级版SDK，QuerySettleBill 分页查询，async 查询等同于同步查询

### ISSUE THREAD

**Issue by spxinjie6** [aliyun/alibabacloud-python-sdk#5]
python: 3.7 
alibabacloud-bssopenapi20171214: 1.0.0
在使用QuerySettleBill之前，我先看的是QueryBill，提示后期不会维护。
当使用分页查询时， 初始NextToken 默认为空即第一页，根据response 返回参数中的NextToken 进行下一页请求
在使用 async 时，效果等同于同步请求，所以，提供的async 完全没有意义。

当我使用async时，肯定是把请求放到 task 中，但是因为分页NextToken 的机制，我就不得不每次只发起一个请求，不能为了async 而async。

最后: QueryBill 虽然不维护，但是pageNum 的使用，可以更好的使用async.
烦请各位大大重视。

**Comment by JacksonTian** [comment]
async 只是为异步提供的版本，有 sync 的版本。分页跟 sync/async 无关。

感谢反馈。
