### ISSUE TITLE
ALB Request 对 Tag 参数的序列化处理存在问题

### ISSUE THREAD

**Issue by ZXiangQAQ** [aliyun/alibabacloud-python-sdk#6]
alb_20200616_models.ListListenersRequest
alb_20200616_models.ListServerGroupsRequest

无论传不传 Tag 参数，to_map() 方法都会先构造 result['Tag'] = [] ，然后再根据传的 Tag 参数进行填充，会导致即使不传 Tag 时，request body 都会带上一个空 Tag，阿里云会直接返回参数错误

Tea.exceptions.TeaException: Error: InvalidTag; Illegal parameter serialization format.

**Comment by shenxgan** [comment]
报错信息：HTTP Status: 400 Error:InvalidServerIds; Illegal parameter serialization format. Flat format is required. Specified parameter ServerIds;

**Comment by TsinghuaDream** [comment]
当前SDK已无此问题。
pip install alibabacloud_nlb20220430==3.0.2
